<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>false</IsAotCompatible>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/MentalDesk.Tui/MentalDesk.Tui.csproj" />
    <ProjectReference Include="../../src/Swatch/Swatch.csproj" />
  </ItemGroup>

</Project>
