<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MentalDesk.Tui</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Theming/themes.json" LogicalName="MentalDesk.Tui.themes.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MentalDesk.Tui.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Terminal.Gui" Version="2.1.0" />
  </ItemGroup>

</Project>
